<template>
  <v-card elevation="3">
    <v-toolbar elevation="1">
      <v-toolbar-title>{{ $t('changeYourCurrentPassword') }}</v-toolbar-title>
      <v-spacer />
    </v-toolbar>
    <v-form
      ref="form"
      v-model="valid"
    >
      <v-text-field
        v-model="old_pwd"
        class="ml-5 mr-5"
        :label="$t('oldPassword')"
        :type="showPassword ? 'password' : 'text'"
        :append-icon="showPassword ? 'mdi-eye-off' : 'mdi-eye'"
        counter="true"
        :rules="[required('password'), minLength('password', 8)]"
        @click:append="showPassword = !showPassword"
      />

      <v-text-field
        v-model="new_pwd"
        class="ml-5 mr-5"
        :label="$t('newPassword')"
        :type="showPassword ? 'password' : 'text'"
        :append-icon="showPassword ? 'mdi-eye-off' : 'mdi-eye'"
        counter="true"
        :rules="[required('password'), minLength('password', 8)]"
        @click:append="showPassword = !showPassword"
      />

      <v-checkbox
        v-model="checkbox"
        class="ml-5"
        :rules="[v => !!v || 'You must agree to continue!']"
        :label="$t('isInformationCorrect')"
        required
      />

      <v-btn
        class="ml-5 mb-5"
        color="success"
        :disabled="!valid"
        @click="changePwd()"
      >
        {{ $t('submit') }}
      </v-btn>
      <v-btn
        class="ml-5 mb-5"
        color="error"
        @click="resetForm()"
      >
        {{ $t('resetForm') }}
      </v-btn>
    </v-form>
  </v-card>
</template>

<script>
import axios from 'axios'
import validations from '@/utils/validations'

export default {
  name: 'UserChanges',
  data: () => ({
    valid: true,
    showPassword: true,
    formData: null,
    old_pwd: '',
    new_pwd: '',
    checkbox: false,
    ...validations
  }),
  methods: {
    /**
     * PUT request to get a new autogenerated password
     * for the authenticated user.
     */
    changePwd () {
      this.formData = new FormData()
      this.formData.append('old', this.old_pwd)
      this.formData.append('new', this.new_pwd)
      axios({
        url: 'http://212.227.210.204:8765/user/change_password',
        method: 'PUT',
        headers: {
          'Content-Type': 'multipart/form-data',
          // 'Content-Type': 'application/json; charset=utf-8'
          Authorization: this.$auth.getToken('local')
        },
        data: this.formData
      }).then((response) => {
        this.$router.push('/user')
      }).catch((error) => {
        console.log('in catch')
        window.alert('An error occurred. Please try again!')
        const response = error.response
        console.log(JSON.stringify(response.data.errors))
      })
      this.resetForm()
    },

    /**
     * Resets the fields of the form.
     */
    resetForm () {
      this.$refs.form.reset()
    }
  }
}
</script>

<style scoped>

</style>
